export type ComponentStatus = "stable" | "beta";

export interface ComponentMeta {
  slug: string;
  name: string;
  category: "Action" | "Display" | "Form" | "Navigation" | "Overlay" | "Feedback";
  status: ComponentStatus;
  tags: string[];
  summary: string;
  usage: string;
  do: string[];
  dont: string[];
}

export const categories = [
  { name: "Action", color: "bg-blue-500", items: ["Button", "Button Group", "Dropdown Menu", "Icon Button", "Link", "More Menu"] },
  { name: "Display", color: "bg-teal-500", items: ["Avatar", "Badge", "Card", "Code Block", "Divider", "Empty State"] },
  { name: "Form", color: "bg-violet-500", items: ["Input", "Checkbox", "Select", "Toggle"] },
  { name: "Navigation", color: "bg-orange-500", items: ["Tabs", "Breadcrumbs", "Pagination"] },
  { name: "Overlay", color: "bg-pink-500", items: ["Modal", "Tooltip"] },
  { name: "Feedback", color: "bg-emerald-500", items: ["Alert", "Toast", "Spinner"] },
] as const;

export const components: ComponentMeta[] = [
  {
    slug: "button",
    name: "Button",
    category: "Action",
    status: "stable",
    tags: ["interactive", "form"],
    summary: "Trigger an action or event, such as submitting a form or opening a dialog.",
    usage:
      "Use it for form submissions, confirmations, navigation, or any interaction that needs a clear call to action.",
    do: [
      "Reserve primary for the single most important action in the view. Use secondary or ghost for everything else.",
      'Write labels that describe the action ("Save changes", "Delete account"). Avoid vague labels like "OK" or "Click here".',
      "Show a loading state for actions that take time, like saving or submitting, so the user knows it is working.",
    ],
    dont: [
      "Place more than one primary button in the same view — this dilutes the visual hierarchy.",
      "Use the destructive variant without a confirmation step for irreversible actions like deleting data.",
      "Use a button for navigation. If it only takes the user to another page, use a link instead.",
    ],
  },
  {
    slug: "button-group",
    name: "Button Group",
    category: "Action",
    status: "stable",
    tags: ["interactive"],
    summary: "A set of related buttons, visually grouped together as a single control.",
    usage: "Use for segmented choices like view toggles (grid/list) or grouped filters.",
    do: ["Keep labels short so groups stay compact.", "Use for mutually exclusive choices."],
    dont: ["Mix unrelated actions in a single group.", "Use more than 4-5 items in a group."],
  },
  {
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    category: "Action",
    status: "stable",
    tags: ["interactive", "overlay"],
    summary: "A menu of actions or options revealed by a trigger.",
    usage: "Use when there are more actions than can fit inline.",
    do: ["Group related items with dividers.", "Order items by frequency of use."],
    dont: ["Nest more than one level of submenu.", "Hide destructive actions among safe ones without separation."],
  },
  {
    slug: "icon-button",
    name: "Icon Button",
    category: "Action",
    status: "stable",
    tags: ["interactive"],
    summary: "A compact button that uses only an icon to represent its action.",
    usage: "Use in toolbars and dense UI where a label would take too much space.",
    do: ["Always pair with an accessible label / tooltip.", "Use recognizable, standard icons."],
    dont: ["Use for critical or destructive actions without confirmation.", "Use ambiguous or custom icons without a label."],
  },
  {
    slug: "link",
    name: "Link",
    category: "Action",
    status: "stable",
    tags: ["navigation"],
    summary: "Navigates the user to another page, section, or resource.",
    usage: "Use for navigation. Use a button when the interaction triggers an action instead.",
    do: ["Underline or clearly distinguish inline links from body text.", "Use descriptive link text."],
    dont: ['Use "click here" as link text.', "Style a link to look like a button if it performs an action."],
  },
  {
    slug: "more-menu",
    name: "More Menu",
    category: "Action",
    status: "beta",
    tags: ["interactive"],
    summary: "An overflow menu (kebab / ellipsis) for secondary or less-used actions.",
    usage: "Use in table rows, cards, or toolbars to house actions that don't need to be primary.",
    do: ["Keep the most common action easy to reach even when hidden here.", "Limit to 3-7 items."],
    dont: ["Hide the primary action of a row inside this menu.", "Use for the only action available — just show it directly."],
  },
  {
    slug: "avatar",
    name: "Avatar",
    category: "Display",
    status: "stable",
    tags: ["display"],
    summary: "A visual representation of a user, team, or entity.",
    usage: "Use in tables, comments, headers, and anywhere identity needs to be shown.",
    do: ["Provide a fallback (initials) when no image is available.", "Keep sizes consistent within the same context."],
    dont: ["Use avatars for non-identity imagery.", "Stretch or distort the image to fit the shape."],
  },
  {
    slug: "badge",
    name: "Badge",
    category: "Display",
    status: "stable",
    tags: ["display"],
    summary: "A small label used to highlight status, category, or count.",
    usage: "Use for statuses (Paid, Pending, Overdue), counts, or tags.",
    do: ["Use consistent colors for the same meaning across the product.", "Keep badge text short — one or two words."],
    dont: ["Use more than one badge per item unless necessary.", "Rely on color alone to convey meaning — add text too."],
  },
  {
    slug: "card",
    name: "Card",
    category: "Display",
    status: "stable",
    tags: ["display", "layout"],
    summary: "A container that groups related content and actions.",
    usage: "Use to group content into digestible, scannable sections.",
    do: ["Keep consistent padding and radius across cards.", "Use a clear hierarchy inside — title, body, action."],
    dont: ["Nest cards inside cards.", "Overload a single card with unrelated content."],
  },
  {
    slug: "code-block",
    name: "Code Block",
    category: "Display",
    status: "stable",
    tags: ["display"],
    summary: "Displays formatted, syntax-highlighted code snippets.",
    usage: "Use in documentation and usage examples.",
    do: ["Include a copy button.", "Keep line length reasonable, wrap when needed."],
    dont: ["Use for non-code content.", "Omit language context when it aids readability."],
  },
  {
    slug: "divider",
    name: "Divider",
    category: "Display",
    status: "stable",
    tags: ["display"],
    summary: "A thin line used to separate content into distinct sections.",
    usage: "Use sparingly to group related content without adding a full container.",
    do: ["Use consistent spacing above and below.", "Use as a lighter alternative to a card border."],
    dont: ["Overuse — too many dividers create visual noise.", "Use as a replacement for proper spacing."],
  },
  {
    slug: "empty-state",
    name: "Empty State",
    category: "Display",
    status: "stable",
    tags: ["display"],
    summary: "Communicates that there is no content to show, with a next step.",
    usage: "Use for empty tables, search results, or first-run experiences.",
    do: ["Explain why it's empty and what to do next.", "Include a clear primary action when applicable."],
    dont: ["Leave a blank screen with no explanation.", "Use overly technical language."],
  },
  {
    slug: "input",
    name: "Input",
    category: "Form",
    status: "stable",
    tags: ["form", "interactive"],
    summary: "A field for entering short text, numbers, or other data.",
    usage: "Use for single-line text entry in forms.",
    do: ["Always pair with a visible label.", "Show inline validation errors close to the field."],
    dont: ["Use placeholder text as a substitute for a label.", "Disable a field without explaining why."],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    category: "Form",
    status: "stable",
    tags: ["form", "interactive"],
    summary: "Lets users select one or more options from a set.",
    usage: "Use for multi-select choices or binary settings.",
    do: ["Group related checkboxes with a clear label.", "Support an indeterminate state for partial selection."],
    dont: ["Use checkboxes for mutually exclusive options — use radio buttons instead.", "Hide the selection state visually."],
  },
  {
    slug: "select",
    name: "Select",
    category: "Form",
    status: "stable",
    tags: ["form", "interactive"],
    summary: "Lets users choose one option from a list in a dropdown.",
    usage: "Use when there are many options and space is limited.",
    do: ["Sort long lists logically (alphabetical, frequency).", "Support search/filter for long lists."],
    dont: ["Use for fewer than 3 options — consider a button group or radio instead.", "Pre-select an option that could cause harm if unnoticed."],
  },
  {
    slug: "toggle",
    name: "Toggle",
    category: "Form",
    status: "beta",
    tags: ["form", "interactive"],
    summary: "A switch for turning a single setting on or off.",
    usage: "Use for binary settings that take effect immediately.",
    do: ["Apply the change immediately, without a separate save step.", "Label clearly what the on/off state means."],
    dont: ["Use for actions that need confirmation before applying.", "Use ambiguous labels where on/off meaning is unclear."],
  },
  {
    slug: "tabs",
    name: "Tabs",
    category: "Navigation",
    status: "stable",
    tags: ["navigation"],
    summary: "Organizes content into separate views within the same context.",
    usage: "Use to switch between related views without navigating away from the page.",
    do: ["Keep tab labels short and parallel in structure.", "Limit to a manageable number of tabs (up to ~6-7)."],
    dont: ["Use tabs for sequential steps — use a stepper instead.", "Hide critical information behind a non-default tab."],
  },
  {
    slug: "breadcrumbs",
    name: "Breadcrumbs",
    category: "Navigation",
    status: "stable",
    tags: ["navigation"],
    summary: "Shows the user's location within a hierarchy and allows quick backtracking.",
    usage: "Use in deep or nested page structures.",
    do: ["Reflect the actual hierarchy of the site.", "Make all but the current page clickable."],
    dont: ["Use on flat, single-level sites.", "Make the current page a clickable link."],
  },
  {
    slug: "pagination",
    name: "Pagination",
    category: "Navigation",
    status: "stable",
    tags: ["navigation"],
    summary: "Splits large sets of content across multiple pages.",
    usage: "Use for tables or lists with many items.",
    do: ["Show the current page and total clearly.", "Consider infinite scroll for casual browsing contexts instead."],
    dont: ["Hide how many pages/items exist in total.", "Reset scroll position unexpectedly on page change."],
  },
  {
    slug: "modal",
    name: "Modal",
    category: "Overlay",
    status: "stable",
    tags: ["overlay", "interactive"],
    summary: "A dialog that interrupts the current context to focus the user on a task.",
    usage: "Use for focused tasks, confirmations, or critical information that needs immediate attention.",
    do: ["Provide a clear way to dismiss (close button, escape key, backdrop click).", "Keep content focused on a single task."],
    dont: ["Stack multiple modals on top of each other.", "Use for content that could be a regular page or panel."],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    category: "Overlay",
    status: "stable",
    tags: ["overlay"],
    summary: "A small popup that shows brief, supplementary information on hover or focus.",
    usage: "Use to clarify icon-only buttons or provide extra context.",
    do: ["Keep the text short — a phrase, not a paragraph.", "Ensure it's accessible via keyboard focus, not just hover."],
    dont: ["Put essential information only in a tooltip.", "Use for content that requires interaction — use a popover instead."],
  },
  {
    slug: "alert",
    name: "Alert",
    category: "Feedback",
    status: "stable",
    tags: ["feedback"],
    summary: "A persistent, inline message that communicates important information.",
    usage: "Use for warnings, errors, or important contextual information tied to a section of the page.",
    do: ["Match color and icon to severity (info, success, warning, error).", "Keep messages actionable and specific."],
    dont: ["Use for transient confirmations — use a toast instead.", "Overuse alerts for low-priority information."],
  },
  {
    slug: "toast",
    name: "Toast",
    category: "Feedback",
    status: "beta",
    tags: ["feedback"],
    summary: "A brief, temporary notification that appears and disappears automatically.",
    usage: "Use to confirm the result of an action, like saving or sending.",
    do: ["Auto-dismiss after a few seconds.", "Keep the message short and specific to what just happened."],
    dont: ["Use for critical errors that require action — use an alert or modal instead.", "Stack too many toasts at once."],
  },
  {
    slug: "spinner",
    name: "Spinner",
    category: "Feedback",
    status: "stable",
    tags: ["feedback"],
    summary: "Indicates that content is loading or an action is in progress.",
    usage: "Use for short waits. For longer operations, consider a progress bar with more context.",
    do: ["Pair with a label when the wait may be longer than a second or two.", "Use consistent sizing across similar contexts."],
    dont: ["Use a spinner for waits long enough to need progress feedback.", "Leave the user without any indication that something is happening."],
  },
];

export function getComponent(slug: string) {
  return components.find((c) => c.slug === slug);
}

export function componentsByCategory(category: string) {
  return components.filter((c) => c.category === category);
}
